package app;

import android.support.v7.appcompat.C0057R;
import se.emilsjolander.stickylistheaders.C1128R;

/* renamed from: app.R */
public final class C0110R {

    /* renamed from: app.R.styleable */
    public final class styleable {
        public static final int[] ActionBar;
        public static final int[] ActionBarLayout;
        public static final int ActionBarLayout_android_layout_gravity = 0;
        public static final int ActionBar_background = 10;
        public static final int ActionBar_backgroundSplit = 12;
        public static final int ActionBar_backgroundStacked = 11;
        public static final int ActionBar_contentInsetEnd = 21;
        public static final int ActionBar_contentInsetLeft = 22;
        public static final int ActionBar_contentInsetRight = 23;
        public static final int ActionBar_contentInsetStart = 20;
        public static final int ActionBar_customNavigationLayout = 13;
        public static final int ActionBar_displayOptions = 3;
        public static final int ActionBar_divider = 9;
        public static final int ActionBar_elevation = 24;
        public static final int ActionBar_height = 0;
        public static final int ActionBar_hideOnContentScroll = 19;
        public static final int ActionBar_homeAsUpIndicator = 26;
        public static final int ActionBar_homeLayout = 14;
        public static final int ActionBar_icon = 7;
        public static final int ActionBar_indeterminateProgressStyle = 16;
        public static final int ActionBar_itemPadding = 18;
        public static final int ActionBar_logo = 8;
        public static final int ActionBar_navigationMode = 2;
        public static final int ActionBar_popupTheme = 25;
        public static final int ActionBar_progressBarPadding = 17;
        public static final int ActionBar_progressBarStyle = 15;
        public static final int ActionBar_subtitle = 4;
        public static final int ActionBar_subtitleTextStyle = 6;
        public static final int ActionBar_title = 1;
        public static final int ActionBar_titleTextStyle = 5;
        public static final int[] ActionMenuItemView;
        public static final int ActionMenuItemView_android_minWidth = 0;
        public static final int[] ActionMenuView;
        public static final int[] ActionMode;
        public static final int ActionMode_background = 3;
        public static final int ActionMode_backgroundSplit = 4;
        public static final int ActionMode_closeItemLayout = 5;
        public static final int ActionMode_height = 0;
        public static final int ActionMode_subtitleTextStyle = 2;
        public static final int ActionMode_titleTextStyle = 1;
        public static final int[] ActivityChooserView;
        public static final int ActivityChooserView_expandActivityOverflowButtonDrawable = 1;
        public static final int ActivityChooserView_initialActivityCount = 0;
        public static final int[] AlertDialog;
        public static final int AlertDialog_android_layout = 0;
        public static final int AlertDialog_buttonPanelSideLayout = 1;
        public static final int AlertDialog_listItemLayout = 5;
        public static final int AlertDialog_listLayout = 2;
        public static final int AlertDialog_multiChoiceItemLayout = 3;
        public static final int AlertDialog_singleChoiceItemLayout = 4;
        public static final int[] AppCompatTextView;
        public static final int AppCompatTextView_android_textAppearance = 0;
        public static final int AppCompatTextView_textAllCaps = 1;
        public static final int[] ArcLayout;
        public static final int ArcLayout_childSize = 0;
        public static final int ArcLayout_fromDegrees = 1;
        public static final int ArcLayout_toDegrees = 2;
        public static final int[] ArcMenu;
        public static final int ArcMenu_childSize = 0;
        public static final int ArcMenu_fromDegrees = 1;
        public static final int ArcMenu_toDegrees = 2;
        public static final int[] AutofitTextView;
        public static final int AutofitTextView_minTextSize = 0;
        public static final int AutofitTextView_precision = 1;
        public static final int AutofitTextView_sizeToFit = 2;
        public static final int[] ButtonBarLayout;
        public static final int ButtonBarLayout_allowStacking = 0;
        public static final int[] CompoundButton;
        public static final int CompoundButton_android_button = 0;
        public static final int CompoundButton_buttonTint = 1;
        public static final int CompoundButton_buttonTintMode = 2;
        public static final int[] CropImageView;
        public static final int CropImageView_aspectRatioX = 2;
        public static final int CropImageView_aspectRatioY = 3;
        public static final int CropImageView_fixAspectRatio = 1;
        public static final int CropImageView_guidelines = 0;
        public static final int CropImageView_imageResource = 4;
        public static final int[] DrawerArrowToggle;
        public static final int DrawerArrowToggle_arrowHeadLength = 4;
        public static final int DrawerArrowToggle_arrowShaftLength = 5;
        public static final int DrawerArrowToggle_barLength = 6;
        public static final int DrawerArrowToggle_color = 0;
        public static final int DrawerArrowToggle_drawableSize = 2;
        public static final int DrawerArrowToggle_gapBetweenBars = 3;
        public static final int DrawerArrowToggle_spinBars = 1;
        public static final int DrawerArrowToggle_thickness = 7;
        public static final int[] ExpandableLayout;
        public static final int ExpandableLayout_animationDuration = 3;
        public static final int ExpandableLayout_collapsedWidth = 2;
        public static final int ExpandableLayout_content = 1;
        public static final int ExpandableLayout_handle = 0;
        public static final int[] LinearLayoutCompat;
        public static final int[] LinearLayoutCompat_Layout;
        public static final int LinearLayoutCompat_Layout_android_layout_gravity = 0;
        public static final int LinearLayoutCompat_Layout_android_layout_height = 2;
        public static final int LinearLayoutCompat_Layout_android_layout_weight = 3;
        public static final int LinearLayoutCompat_Layout_android_layout_width = 1;
        public static final int LinearLayoutCompat_android_baselineAligned = 2;
        public static final int LinearLayoutCompat_android_baselineAlignedChildIndex = 3;
        public static final int LinearLayoutCompat_android_gravity = 0;
        public static final int LinearLayoutCompat_android_orientation = 1;
        public static final int LinearLayoutCompat_android_weightSum = 4;
        public static final int LinearLayoutCompat_divider = 5;
        public static final int LinearLayoutCompat_dividerPadding = 8;
        public static final int LinearLayoutCompat_measureWithLargestChild = 6;
        public static final int LinearLayoutCompat_showDividers = 7;
        public static final int[] ListPopupWindow;
        public static final int ListPopupWindow_android_dropDownHorizontalOffset = 0;
        public static final int ListPopupWindow_android_dropDownVerticalOffset = 1;
        public static final int[] LoadingImageView;
        public static final int LoadingImageView_circleCrop = 2;
        public static final int LoadingImageView_imageAspectRatio = 1;
        public static final int LoadingImageView_imageAspectRatioAdjust = 0;
        public static final int[] MapAttrs;
        public static final int MapAttrs_ambientEnabled = 16;
        public static final int MapAttrs_cameraBearing = 1;
        public static final int MapAttrs_cameraTargetLat = 2;
        public static final int MapAttrs_cameraTargetLng = 3;
        public static final int MapAttrs_cameraTilt = 4;
        public static final int MapAttrs_cameraZoom = 5;
        public static final int MapAttrs_liteMode = 6;
        public static final int MapAttrs_mapType = 0;
        public static final int MapAttrs_uiCompass = 7;
        public static final int MapAttrs_uiMapToolbar = 15;
        public static final int MapAttrs_uiRotateGestures = 8;
        public static final int MapAttrs_uiScrollGestures = 9;
        public static final int MapAttrs_uiTiltGestures = 10;
        public static final int MapAttrs_uiZoomControls = 11;
        public static final int MapAttrs_uiZoomGestures = 12;
        public static final int MapAttrs_useViewLifecycle = 13;
        public static final int MapAttrs_zOrderOnTop = 14;
        public static final int[] MenuGroup;
        public static final int MenuGroup_android_checkableBehavior = 5;
        public static final int MenuGroup_android_enabled = 0;
        public static final int MenuGroup_android_id = 1;
        public static final int MenuGroup_android_menuCategory = 3;
        public static final int MenuGroup_android_orderInCategory = 4;
        public static final int MenuGroup_android_visible = 2;
        public static final int[] MenuItem;
        public static final int MenuItem_actionLayout = 14;
        public static final int MenuItem_actionProviderClass = 16;
        public static final int MenuItem_actionViewClass = 15;
        public static final int MenuItem_android_alphabeticShortcut = 9;
        public static final int MenuItem_android_checkable = 11;
        public static final int MenuItem_android_checked = 3;
        public static final int MenuItem_android_enabled = 1;
        public static final int MenuItem_android_icon = 0;
        public static final int MenuItem_android_id = 2;
        public static final int MenuItem_android_menuCategory = 5;
        public static final int MenuItem_android_numericShortcut = 10;
        public static final int MenuItem_android_onClick = 12;
        public static final int MenuItem_android_orderInCategory = 6;
        public static final int MenuItem_android_title = 7;
        public static final int MenuItem_android_titleCondensed = 8;
        public static final int MenuItem_android_visible = 4;
        public static final int MenuItem_showAsAction = 13;
        public static final int[] MenuView;
        public static final int MenuView_android_headerBackground = 4;
        public static final int MenuView_android_horizontalDivider = 2;
        public static final int MenuView_android_itemBackground = 5;
        public static final int MenuView_android_itemIconDisabledAlpha = 6;
        public static final int MenuView_android_itemTextAppearance = 1;
        public static final int MenuView_android_verticalDivider = 3;
        public static final int MenuView_android_windowAnimationStyle = 0;
        public static final int MenuView_preserveIconSpacing = 7;
        public static final int[] NumberPicker;
        public static final int NumberPicker_internalLayout = 8;
        public static final int NumberPicker_internalMaxHeight = 5;
        public static final int NumberPicker_internalMaxWidth = 7;
        public static final int NumberPicker_internalMinHeight = 4;
        public static final int NumberPicker_internalMinWidth = 6;
        public static final int NumberPicker_selectionDivider = 1;
        public static final int NumberPicker_selectionDividerHeight = 2;
        public static final int NumberPicker_selectionDividersDistance = 3;
        public static final int NumberPicker_solidColor = 0;
        public static final int NumberPicker_virtualButtonPressedDrawable = 9;
        public static final int[] ParallaxScroll;
        public static final int ParallaxScroll_alpha_factor = 1;
        public static final int ParallaxScroll_inner_parallax_factor = 2;
        public static final int ParallaxScroll_parallax_factor = 0;
        public static final int ParallaxScroll_parallax_views_num = 3;
        public static final int[] PopupWindow;
        public static final int[] PopupWindowBackgroundState;
        public static final int PopupWindowBackgroundState_state_above_anchor = 0;
        public static final int PopupWindow_android_popupBackground = 0;
        public static final int PopupWindow_overlapAnchor = 1;
        public static final int[] ProgressWheel;
        public static final int ProgressWheel_barColor = 3;
        public static final int ProgressWheel_barLeng = 11;
        public static final int ProgressWheel_barWidth = 10;
        public static final int ProgressWheel_circleColor = 8;
        public static final int ProgressWheel_contourColor = 12;
        public static final int ProgressWheel_contourSize = 13;
        public static final int ProgressWheel_delayMillis = 7;
        public static final int ProgressWheel_radius = 9;
        public static final int ProgressWheel_rimColor = 4;
        public static final int ProgressWheel_rimWidth = 5;
        public static final int ProgressWheel_spinSpeed = 6;
        public static final int ProgressWheel_text = 0;
        public static final int ProgressWheel_textColor = 1;
        public static final int ProgressWheel_textSize = 2;
        public static final int[] RayLayout;
        public static final int RayLayout_leftHolderWidth = 0;
        public static final int[] RecyclerView;
        public static final int RecyclerView_android_orientation = 0;
        public static final int RecyclerView_layoutManager = 1;
        public static final int RecyclerView_reverseLayout = 3;
        public static final int RecyclerView_spanCount = 2;
        public static final int RecyclerView_stackFromEnd = 4;
        public static final int[] RoundCornerProgress;
        public static final int RoundCornerProgress_rcAutoTextChange = 16;
        public static final int RoundCornerProgress_rcBackgroundColor = 9;
        public static final int RoundCornerProgress_rcBackgroundPadding = 1;
        public static final int RoundCornerProgress_rcBackgroundRadius = 2;
        public static final int RoundCornerProgress_rcHeaderColor = 7;
        public static final int RoundCornerProgress_rcIconPadding = 6;
        public static final int RoundCornerProgress_rcIconSize = 5;
        public static final int RoundCornerProgress_rcIconSrc = 4;
        public static final int RoundCornerProgress_rcMax = 3;
        public static final int RoundCornerProgress_rcProgress = 0;
        public static final int RoundCornerProgress_rcProgressColor = 8;
        public static final int RoundCornerProgress_rcSecondaryProgress = 17;
        public static final int RoundCornerProgress_rcSecondaryProgressColor = 18;
        public static final int RoundCornerProgress_rcTextProgress = 11;
        public static final int RoundCornerProgress_rcTextProgressColor = 10;
        public static final int RoundCornerProgress_rcTextProgressPadding = 15;
        public static final int RoundCornerProgress_rcTextProgressSize = 13;
        public static final int RoundCornerProgress_rcTextProgressUnit = 12;
        public static final int RoundCornerProgress_rcTextProgressWidth = 14;
        public static final int[] RoundedImageView;
        public static final int RoundedImageView_android_scaleType = 0;
        public static final int RoundedImageView_riv_border_color = 7;
        public static final int RoundedImageView_riv_border_width = 6;
        public static final int RoundedImageView_riv_corner_radius = 1;
        public static final int RoundedImageView_riv_corner_radius_bottom_left = 4;
        public static final int RoundedImageView_riv_corner_radius_bottom_right = 5;
        public static final int RoundedImageView_riv_corner_radius_top_left = 2;
        public static final int RoundedImageView_riv_corner_radius_top_right = 3;
        public static final int RoundedImageView_riv_mutate_background = 8;
        public static final int RoundedImageView_riv_oval = 9;
        public static final int RoundedImageView_riv_tile_mode = 10;
        public static final int RoundedImageView_riv_tile_mode_x = 11;
        public static final int RoundedImageView_riv_tile_mode_y = 12;
        public static final int[] SearchView;
        public static final int SearchView_android_focusable = 0;
        public static final int SearchView_android_imeOptions = 3;
        public static final int SearchView_android_inputType = 2;
        public static final int SearchView_android_maxWidth = 1;
        public static final int SearchView_closeIcon = 8;
        public static final int SearchView_commitIcon = 13;
        public static final int SearchView_defaultQueryHint = 7;
        public static final int SearchView_goIcon = 9;
        public static final int SearchView_iconifiedByDefault = 5;
        public static final int SearchView_layout = 4;
        public static final int SearchView_queryBackground = 15;
        public static final int SearchView_queryHint = 6;
        public static final int SearchView_searchHintIcon = 11;
        public static final int SearchView_searchIcon = 10;
        public static final int SearchView_submitBackground = 16;
        public static final int SearchView_suggestionRowLayout = 14;
        public static final int SearchView_voiceIcon = 12;
        public static final int[] Spinner;
        public static final int Spinner_android_dropDownWidth = 2;
        public static final int Spinner_android_popupBackground = 0;
        public static final int Spinner_android_prompt = 1;
        public static final int Spinner_popupTheme = 3;
        public static final int[] StickyListHeadersListView;
        public static final int StickyListHeadersListView_android_cacheColorHint = 14;
        public static final int StickyListHeadersListView_android_choiceMode = 17;
        public static final int StickyListHeadersListView_android_clipToPadding = 8;
        public static final int StickyListHeadersListView_android_divider = 15;
        public static final int StickyListHeadersListView_android_dividerHeight = 16;
        public static final int StickyListHeadersListView_android_drawSelectorOnTop = 10;
        public static final int StickyListHeadersListView_android_fadingEdgeLength = 7;
        public static final int StickyListHeadersListView_android_fastScrollAlwaysVisible = 20;
        public static final int StickyListHeadersListView_android_fastScrollEnabled = 18;
        public static final int StickyListHeadersListView_android_listSelector = 9;
        public static final int StickyListHeadersListView_android_overScrollMode = 19;
        public static final int StickyListHeadersListView_android_padding = 1;
        public static final int StickyListHeadersListView_android_paddingBottom = 5;
        public static final int StickyListHeadersListView_android_paddingLeft = 2;
        public static final int StickyListHeadersListView_android_paddingRight = 4;
        public static final int StickyListHeadersListView_android_paddingTop = 3;
        public static final int StickyListHeadersListView_android_requiresFadingEdge = 21;
        public static final int StickyListHeadersListView_android_scrollbarStyle = 0;
        public static final int StickyListHeadersListView_android_scrollbars = 6;
        public static final int StickyListHeadersListView_android_scrollingCache = 12;
        public static final int StickyListHeadersListView_android_stackFromBottom = 11;
        public static final int StickyListHeadersListView_android_transcriptMode = 13;
        public static final int StickyListHeadersListView_hasStickyHeaders = 23;
        public static final int StickyListHeadersListView_isDrawingListUnderStickyHeader = 24;
        public static final int StickyListHeadersListView_stickyListHeadersListViewStyle = 22;
        public static final int[] SwitchCompat;
        public static final int SwitchCompat_android_textOff = 1;
        public static final int SwitchCompat_android_textOn = 0;
        public static final int SwitchCompat_android_thumb = 2;
        public static final int SwitchCompat_showText = 9;
        public static final int SwitchCompat_splitTrack = 8;
        public static final int SwitchCompat_switchMinWidth = 6;
        public static final int SwitchCompat_switchPadding = 7;
        public static final int SwitchCompat_switchTextAppearance = 5;
        public static final int SwitchCompat_thumbTextPadding = 4;
        public static final int SwitchCompat_track = 3;
        public static final int[] TextAppearance;
        public static final int TextAppearance_android_shadowColor = 4;
        public static final int TextAppearance_android_shadowDx = 5;
        public static final int TextAppearance_android_shadowDy = 6;
        public static final int TextAppearance_android_shadowRadius = 7;
        public static final int TextAppearance_android_textColor = 3;
        public static final int TextAppearance_android_textSize = 0;
        public static final int TextAppearance_android_textStyle = 2;
        public static final int TextAppearance_android_typeface = 1;
        public static final int TextAppearance_textAllCaps = 8;
        public static final int[] Theme;
        public static final int Theme_actionBarDivider = 23;
        public static final int Theme_actionBarItemBackground = 24;
        public static final int Theme_actionBarPopupTheme = 17;
        public static final int Theme_actionBarSize = 22;
        public static final int Theme_actionBarSplitStyle = 19;
        public static final int Theme_actionBarStyle = 18;
        public static final int Theme_actionBarTabBarStyle = 13;
        public static final int Theme_actionBarTabStyle = 12;
        public static final int Theme_actionBarTabTextStyle = 14;
        public static final int Theme_actionBarTheme = 20;
        public static final int Theme_actionBarWidgetTheme = 21;
        public static final int Theme_actionButtonStyle = 49;
        public static final int Theme_actionDropDownStyle = 45;
        public static final int Theme_actionMenuTextAppearance = 25;
        public static final int Theme_actionMenuTextColor = 26;
        public static final int Theme_actionModeBackground = 29;
        public static final int Theme_actionModeCloseButtonStyle = 28;
        public static final int Theme_actionModeCloseDrawable = 31;
        public static final int Theme_actionModeCopyDrawable = 33;
        public static final int Theme_actionModeCutDrawable = 32;
        public static final int Theme_actionModeFindDrawable = 37;
        public static final int Theme_actionModePasteDrawable = 34;
        public static final int Theme_actionModePopupWindowStyle = 39;
        public static final int Theme_actionModeSelectAllDrawable = 35;
        public static final int Theme_actionModeShareDrawable = 36;
        public static final int Theme_actionModeSplitBackground = 30;
        public static final int Theme_actionModeStyle = 27;
        public static final int Theme_actionModeWebSearchDrawable = 38;
        public static final int Theme_actionOverflowButtonStyle = 15;
        public static final int Theme_actionOverflowMenuStyle = 16;
        public static final int Theme_activityChooserViewStyle = 57;
        public static final int Theme_alertDialogButtonGroupStyle = 92;
        public static final int Theme_alertDialogCenterButtons = 93;
        public static final int Theme_alertDialogStyle = 91;
        public static final int Theme_alertDialogTheme = 94;
        public static final int Theme_android_windowAnimationStyle = 1;
        public static final int Theme_android_windowIsFloating = 0;
        public static final int Theme_autoCompleteTextViewStyle = 99;
        public static final int Theme_borderlessButtonStyle = 54;
        public static final int Theme_buttonBarButtonStyle = 51;
        public static final int Theme_buttonBarNegativeButtonStyle = 97;
        public static final int Theme_buttonBarNeutralButtonStyle = 98;
        public static final int Theme_buttonBarPositiveButtonStyle = 96;
        public static final int Theme_buttonBarStyle = 50;
        public static final int Theme_buttonStyle = 100;
        public static final int Theme_buttonStyleSmall = 101;
        public static final int Theme_checkboxStyle = 102;
        public static final int Theme_checkedTextViewStyle = 103;
        public static final int Theme_colorAccent = 84;
        public static final int Theme_colorButtonNormal = 88;
        public static final int Theme_colorControlActivated = 86;
        public static final int Theme_colorControlHighlight = 87;
        public static final int Theme_colorControlNormal = 85;
        public static final int Theme_colorPrimary = 82;
        public static final int Theme_colorPrimaryDark = 83;
        public static final int Theme_colorSwitchThumbNormal = 89;
        public static final int Theme_controlBackground = 90;
        public static final int Theme_dialogPreferredPadding = 43;
        public static final int Theme_dialogTheme = 42;
        public static final int Theme_dividerHorizontal = 56;
        public static final int Theme_dividerVertical = 55;
        public static final int Theme_dropDownListViewStyle = 74;
        public static final int Theme_dropdownListPreferredItemHeight = 46;
        public static final int Theme_editTextBackground = 63;
        public static final int Theme_editTextColor = 62;
        public static final int Theme_editTextStyle = 104;
        public static final int Theme_homeAsUpIndicator = 48;
        public static final int Theme_imageButtonStyle = 64;
        public static final int Theme_listChoiceBackgroundIndicator = 81;
        public static final int Theme_listDividerAlertDialog = 44;
        public static final int Theme_listPopupWindowStyle = 75;
        public static final int Theme_listPreferredItemHeight = 69;
        public static final int Theme_listPreferredItemHeightLarge = 71;
        public static final int Theme_listPreferredItemHeightSmall = 70;
        public static final int Theme_listPreferredItemPaddingLeft = 72;
        public static final int Theme_listPreferredItemPaddingRight = 73;
        public static final int Theme_panelBackground = 78;
        public static final int Theme_panelMenuListTheme = 80;
        public static final int Theme_panelMenuListWidth = 79;
        public static final int Theme_popupMenuStyle = 60;
        public static final int Theme_popupWindowStyle = 61;
        public static final int Theme_radioButtonStyle = 105;
        public static final int Theme_ratingBarStyle = 106;
        public static final int Theme_searchViewStyle = 68;
        public static final int Theme_seekBarStyle = 107;
        public static final int Theme_selectableItemBackground = 52;
        public static final int Theme_selectableItemBackgroundBorderless = 53;
        public static final int Theme_spinnerDropDownItemStyle = 47;
        public static final int Theme_spinnerStyle = 108;
        public static final int Theme_switchStyle = 109;
        public static final int Theme_textAppearanceLargePopupMenu = 40;
        public static final int Theme_textAppearanceListItem = 76;
        public static final int Theme_textAppearanceListItemSmall = 77;
        public static final int Theme_textAppearanceSearchResultSubtitle = 66;
        public static final int Theme_textAppearanceSearchResultTitle = 65;
        public static final int Theme_textAppearanceSmallPopupMenu = 41;
        public static final int Theme_textColorAlertDialogListItem = 95;
        public static final int Theme_textColorSearchUrl = 67;
        public static final int Theme_toolbarNavigationButtonStyle = 59;
        public static final int Theme_toolbarStyle = 58;
        public static final int Theme_windowActionBar = 2;
        public static final int Theme_windowActionBarOverlay = 4;
        public static final int Theme_windowActionModeOverlay = 5;
        public static final int Theme_windowFixedHeightMajor = 9;
        public static final int Theme_windowFixedHeightMinor = 7;
        public static final int Theme_windowFixedWidthMajor = 6;
        public static final int Theme_windowFixedWidthMinor = 8;
        public static final int Theme_windowMinWidthMajor = 10;
        public static final int Theme_windowMinWidthMinor = 11;
        public static final int Theme_windowNoTitle = 3;
        public static final int[] Toolbar;
        public static final int Toolbar_android_gravity = 0;
        public static final int Toolbar_android_minHeight = 1;
        public static final int Toolbar_collapseContentDescription = 19;
        public static final int Toolbar_collapseIcon = 18;
        public static final int Toolbar_contentInsetEnd = 6;
        public static final int Toolbar_contentInsetLeft = 7;
        public static final int Toolbar_contentInsetRight = 8;
        public static final int Toolbar_contentInsetStart = 5;
        public static final int Toolbar_logo = 4;
        public static final int Toolbar_logoDescription = 22;
        public static final int Toolbar_maxButtonHeight = 17;
        public static final int Toolbar_navigationContentDescription = 21;
        public static final int Toolbar_navigationIcon = 20;
        public static final int Toolbar_popupTheme = 9;
        public static final int Toolbar_subtitle = 3;
        public static final int Toolbar_subtitleTextAppearance = 11;
        public static final int Toolbar_subtitleTextColor = 24;
        public static final int Toolbar_title = 2;
        public static final int Toolbar_titleMarginBottom = 16;
        public static final int Toolbar_titleMarginEnd = 14;
        public static final int Toolbar_titleMarginStart = 13;
        public static final int Toolbar_titleMarginTop = 15;
        public static final int Toolbar_titleMargins = 12;
        public static final int Toolbar_titleTextAppearance = 10;
        public static final int Toolbar_titleTextColor = 23;
        public static final int[] View;
        public static final int[] ViewBackgroundHelper;
        public static final int ViewBackgroundHelper_android_background = 0;
        public static final int ViewBackgroundHelper_backgroundTint = 1;
        public static final int ViewBackgroundHelper_backgroundTintMode = 2;
        public static final int[] ViewStubCompat;
        public static final int ViewStubCompat_android_id = 0;
        public static final int ViewStubCompat_android_inflatedId = 2;
        public static final int ViewStubCompat_android_layout = 1;
        public static final int View_android_focusable = 1;
        public static final int View_android_theme = 0;
        public static final int View_paddingEnd = 3;
        public static final int View_paddingStart = 2;
        public static final int View_theme = 4;

        static {
            ActionBar = new int[]{C0057R.attr.height, C0057R.attr.title, C0057R.attr.navigationMode, C0057R.attr.displayOptions, C0057R.attr.subtitle, C0057R.attr.titleTextStyle, C0057R.attr.subtitleTextStyle, C0057R.attr.icon, C0057R.attr.logo, C0057R.attr.divider, C0057R.attr.background, C0057R.attr.backgroundStacked, C0057R.attr.backgroundSplit, C0057R.attr.customNavigationLayout, C0057R.attr.homeLayout, C0057R.attr.progressBarStyle, C0057R.attr.indeterminateProgressStyle, C0057R.attr.progressBarPadding, C0057R.attr.itemPadding, C0057R.attr.hideOnContentScroll, C0057R.attr.contentInsetStart, C0057R.attr.contentInsetEnd, C0057R.attr.contentInsetLeft, C0057R.attr.contentInsetRight, C0057R.attr.elevation, C0057R.attr.popupTheme, C0057R.attr.homeAsUpIndicator};
            int[] iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16842931;
            ActionBarLayout = iArr;
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 16843071;
            ActionMenuItemView = iArr;
            ActionMenuView = new int[View_android_theme];
            ActionMode = new int[]{C0057R.attr.height, C0057R.attr.titleTextStyle, C0057R.attr.subtitleTextStyle, C0057R.attr.background, C0057R.attr.backgroundSplit, C0057R.attr.closeItemLayout};
            ActivityChooserView = new int[]{C0057R.attr.initialActivityCount, C0057R.attr.expandActivityOverflowButtonDrawable};
            AlertDialog = new int[]{16842994, C0057R.attr.buttonPanelSideLayout, C0057R.attr.listLayout, C0057R.attr.multiChoiceItemLayout, C0057R.attr.singleChoiceItemLayout, C0057R.attr.listItemLayout};
            AppCompatTextView = new int[]{16842804, C0057R.attr.textAllCaps};
            ArcLayout = new int[]{2130771968, 2130771970, 2130771975};
            ArcMenu = new int[]{2130771968, 2130771970, 2130771975};
            AutofitTextView = new int[]{2130772009, 2130772010, 2130772011};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = C0057R.attr.allowStacking;
            ButtonBarLayout = iArr;
            CompoundButton = new int[]{16843015, C0057R.attr.buttonTint, C0057R.attr.buttonTintMode};
            CropImageView = new int[]{2130772015, 2130772016, 2130772017, 2130772018, 2130772019};
            DrawerArrowToggle = new int[]{C0057R.attr.color, C0057R.attr.spinBars, C0057R.attr.drawableSize, C0057R.attr.gapBetweenBars, C0057R.attr.arrowHeadLength, C0057R.attr.arrowShaftLength, C0057R.attr.barLength, C0057R.attr.thickness};
            ExpandableLayout = new int[]{2130772028, 2130772029, 2130772030, 2130772031};
            LinearLayoutCompat = new int[]{16842927, 16842948, 16843046, 16843047, 16843048, C0057R.attr.divider, C0057R.attr.measureWithLargestChild, C0057R.attr.showDividers, C0057R.attr.dividerPadding};
            LinearLayoutCompat_Layout = new int[]{16842931, 16842996, 16842997, 16843137};
            ListPopupWindow = new int[]{16843436, 16843437};
            LoadingImageView = new int[]{2130772035, 2130772036, 2130772037};
            MapAttrs = new int[]{2130772038, 2130772039, 2130772040, 2130772041, 2130772042, 2130772043, 2130772044, 2130772045, 2130772046, 2130772047, 2130772048, 2130772049, 2130772050, 2130772051, 2130772052, 2130772053, 2130772054};
            MenuGroup = new int[]{16842766, 16842960, 16843156, 16843230, 16843231, 16843232};
            MenuItem = new int[]{16842754, 16842766, 16842960, 16843014, 16843156, 16843230, 16843231, 16843233, 16843234, 16843235, 16843236, 16843237, 16843375, C0057R.attr.showAsAction, C0057R.attr.actionLayout, C0057R.attr.actionViewClass, C0057R.attr.actionProviderClass};
            MenuView = new int[]{16842926, 16843052, 16843053, 16843054, 16843055, 16843056, 16843057, C0057R.attr.preserveIconSpacing};
            NumberPicker = new int[]{2130772060, 2130772061, 2130772062, 2130772063, 2130772064, 2130772065, 2130772066, 2130772067, 2130772068, 2130772069};
            ParallaxScroll = new int[]{2130772070, 2130772071, 2130772072, 2130772073};
            PopupWindow = new int[]{16843126, C0057R.attr.overlapAnchor};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = C0057R.attr.state_above_anchor;
            PopupWindowBackgroundState = iArr;
            ProgressWheel = new int[]{2130772076, 2130772077, 2130772078, 2130772079, 2130772080, 2130772081, 2130772082, 2130772083, 2130772084, 2130772085, 2130772086, 2130772087, 2130772088, 2130772089};
            iArr = new int[View_android_focusable];
            iArr[View_android_theme] = 2130772090;
            RayLayout = iArr;
            RecyclerView = new int[]{16842948, 2130772091, 2130772092, 2130772093, 2130772094};
            RoundCornerProgress = new int[]{2130772095, 2130772096, 2130772097, 2130772098, 2130772099, 2130772100, 2130772101, 2130772102, 2130772103, 2130772104, 2130772105, 2130772106, 2130772107, 2130772108, 2130772109, 2130772110, 2130772111, 2130772112, 2130772113};
            RoundedImageView = new int[]{16843037, 2130772114, 2130772115, 2130772116, 2130772117, 2130772118, 2130772119, 2130772120, 2130772121, 2130772122, 2130772123, 2130772124, 2130772125};
            SearchView = new int[]{16842970, 16843039, 16843296, 16843364, C0057R.attr.layout, C0057R.attr.iconifiedByDefault, C0057R.attr.queryHint, C0057R.attr.defaultQueryHint, C0057R.attr.closeIcon, C0057R.attr.goIcon, C0057R.attr.searchIcon, C0057R.attr.searchHintIcon, C0057R.attr.voiceIcon, C0057R.attr.commitIcon, C0057R.attr.suggestionRowLayout, C0057R.attr.queryBackground, C0057R.attr.submitBackground};
            Spinner = new int[]{16843126, 16843131, 16843362, C0057R.attr.popupTheme};
            StickyListHeadersListView = new int[]{16842879, 16842965, 16842966, 16842967, 16842968, 16842969, 16842974, 16842976, 16842987, 16843003, 16843004, 16843005, 16843006, 16843008, 16843009, 16843049, 16843050, 16843051, 16843302, 16843457, 16843573, 16843685, C1128R.attr.stickyListHeadersListViewStyle, C1128R.attr.hasStickyHeaders, C1128R.attr.isDrawingListUnderStickyHeader};
            SwitchCompat = new int[]{16843044, 16843045, 16843074, C0057R.attr.track, C0057R.attr.thumbTextPadding, C0057R.attr.switchTextAppearance, C0057R.attr.switchMinWidth, C0057R.attr.switchPadding, C0057R.attr.splitTrack, C0057R.attr.showText};
            TextAppearance = new int[]{16842901, 16842902, 16842903, 16842904, 16843105, 16843106, 16843107, 16843108, C0057R.attr.textAllCaps};
            Theme = new int[]{16842839, 16842926, C0057R.attr.windowActionBar, C0057R.attr.windowNoTitle, C0057R.attr.windowActionBarOverlay, C0057R.attr.windowActionModeOverlay, C0057R.attr.windowFixedWidthMajor, C0057R.attr.windowFixedHeightMinor, C0057R.attr.windowFixedWidthMinor, C0057R.attr.windowFixedHeightMajor, C0057R.attr.windowMinWidthMajor, C0057R.attr.windowMinWidthMinor, C0057R.attr.actionBarTabStyle, C0057R.attr.actionBarTabBarStyle, C0057R.attr.actionBarTabTextStyle, C0057R.attr.actionOverflowButtonStyle, C0057R.attr.actionOverflowMenuStyle, C0057R.attr.actionBarPopupTheme, C0057R.attr.actionBarStyle, C0057R.attr.actionBarSplitStyle, C0057R.attr.actionBarTheme, C0057R.attr.actionBarWidgetTheme, C0057R.attr.actionBarSize, C0057R.attr.actionBarDivider, C0057R.attr.actionBarItemBackground, C0057R.attr.actionMenuTextAppearance, C0057R.attr.actionMenuTextColor, C0057R.attr.actionModeStyle, C0057R.attr.actionModeCloseButtonStyle, C0057R.attr.actionModeBackground, C0057R.attr.actionModeSplitBackground, C0057R.attr.actionModeCloseDrawable, C0057R.attr.actionModeCutDrawable, C0057R.attr.actionModeCopyDrawable, C0057R.attr.actionModePasteDrawable, C0057R.attr.actionModeSelectAllDrawable, C0057R.attr.actionModeShareDrawable, C0057R.attr.actionModeFindDrawable, C0057R.attr.actionModeWebSearchDrawable, C0057R.attr.actionModePopupWindowStyle, C0057R.attr.textAppearanceLargePopupMenu, C0057R.attr.textAppearanceSmallPopupMenu, C0057R.attr.dialogTheme, C0057R.attr.dialogPreferredPadding, C0057R.attr.listDividerAlertDialog, C0057R.attr.actionDropDownStyle, C0057R.attr.dropdownListPreferredItemHeight, C0057R.attr.spinnerDropDownItemStyle, C0057R.attr.homeAsUpIndicator, C0057R.attr.actionButtonStyle, C0057R.attr.buttonBarStyle, C0057R.attr.buttonBarButtonStyle, C0057R.attr.selectableItemBackground, C0057R.attr.selectableItemBackgroundBorderless, C0057R.attr.borderlessButtonStyle, C0057R.attr.dividerVertical, C0057R.attr.dividerHorizontal, C0057R.attr.activityChooserViewStyle, C0057R.attr.toolbarStyle, C0057R.attr.toolbarNavigationButtonStyle, C0057R.attr.popupMenuStyle, C0057R.attr.popupWindowStyle, C0057R.attr.editTextColor, C0057R.attr.editTextBackground, C0057R.attr.imageButtonStyle, C0057R.attr.textAppearanceSearchResultTitle, C0057R.attr.textAppearanceSearchResultSubtitle, C0057R.attr.textColorSearchUrl, C0057R.attr.searchViewStyle, C0057R.attr.listPreferredItemHeight, C0057R.attr.listPreferredItemHeightSmall, C0057R.attr.listPreferredItemHeightLarge, C0057R.attr.listPreferredItemPaddingLeft, C0057R.attr.listPreferredItemPaddingRight, C0057R.attr.dropDownListViewStyle, C0057R.attr.listPopupWindowStyle, C0057R.attr.textAppearanceListItem, C0057R.attr.textAppearanceListItemSmall, C0057R.attr.panelBackground, C0057R.attr.panelMenuListWidth, C0057R.attr.panelMenuListTheme, C0057R.attr.listChoiceBackgroundIndicator, C0057R.attr.colorPrimary, C0057R.attr.colorPrimaryDark, C0057R.attr.colorAccent, C0057R.attr.colorControlNormal, C0057R.attr.colorControlActivated, C0057R.attr.colorControlHighlight, C0057R.attr.colorButtonNormal, C0057R.attr.colorSwitchThumbNormal, C0057R.attr.controlBackground, C0057R.attr.alertDialogStyle, C0057R.attr.alertDialogButtonGroupStyle, C0057R.attr.alertDialogCenterButtons, C0057R.attr.alertDialogTheme, C0057R.attr.textColorAlertDialogListItem, C0057R.attr.buttonBarPositiveButtonStyle, C0057R.attr.buttonBarNegativeButtonStyle, C0057R.attr.buttonBarNeutralButtonStyle, C0057R.attr.autoCompleteTextViewStyle, C0057R.attr.buttonStyle, C0057R.attr.buttonStyleSmall, C0057R.attr.checkboxStyle, C0057R.attr.checkedTextViewStyle, C0057R.attr.editTextStyle, C0057R.attr.radioButtonStyle, C0057R.attr.ratingBarStyle, C0057R.attr.seekBarStyle, C0057R.attr.spinnerStyle, C0057R.attr.switchStyle};
            Toolbar = new int[]{16842927, 16843072, C0057R.attr.title, C0057R.attr.subtitle, C0057R.attr.logo, C0057R.attr.contentInsetStart, C0057R.attr.contentInsetEnd, C0057R.attr.contentInsetLeft, C0057R.attr.contentInsetRight, C0057R.attr.popupTheme, C0057R.attr.titleTextAppearance, C0057R.attr.subtitleTextAppearance, C0057R.attr.titleMargins, C0057R.attr.titleMarginStart, C0057R.attr.titleMarginEnd, C0057R.attr.titleMarginTop, C0057R.attr.titleMarginBottom, C0057R.attr.maxButtonHeight, C0057R.attr.collapseIcon, C0057R.attr.collapseContentDescription, C0057R.attr.navigationIcon, C0057R.attr.navigationContentDescription, C0057R.attr.logoDescription, C0057R.attr.titleTextColor, C0057R.attr.subtitleTextColor};
            View = new int[]{16842752, 16842970, C0057R.attr.paddingStart, C0057R.attr.paddingEnd, C0057R.attr.theme};
            ViewBackgroundHelper = new int[]{16842964, C0057R.attr.backgroundTint, C0057R.attr.backgroundTintMode};
            ViewStubCompat = new int[]{16842960, 16842994, 16842995};
        }
    }
}
